### ISSUE TITLE
Not Actually an Esolang

### ISSUE THREAD

**Issue by hppavilion1** [samshadwell/TrumpScript#10]
Is on the Esolangs wiki, but isn't really that esoteric. More like Lolcode.

**Comment by samshadwell** [comment]
I don't know who added it to that wiki, but after reading this definition:

"An esoteric programming language, or esolang, is a computer programming language designed to experiment with weird ideas, to be hard to program in, or as a joke, rather than for practical use."

I feel like we definitely fit the "as a joke" portion. Also, LOLCODE (which I also just Googled) looks like it's on the list of esoteric languages.
