### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by kool601** [samshadwell/TrumpScript#128]
Why can't we use Windows? Is Trump now being OS'ist!?!? xD. But seriously, please add support for Windows.

**Comment by samshadwell** [comment]
Hey kool601, incompatability with Windows is actually one of the "features" of TrumpScript.

See the README, `In its raw form, TrumpScript is not compatible with Windows, because Trump isn't the type of guy to believe in PC.`

However, if you want to run it on a Windows computer, you can just comment out line 33 in utils.py
