### ISSUE TITLE
Extension should be .trump

### ISSUE THREAD

**Issue by nazieb** [samshadwell/TrumpScript#181]
Trump loves his name to be stamped everywhere.

**Comment by StevenGann** [comment]
I propose .djt (Donald J Trump).

True conservatives hold to three-character extensions. It’s like in golf. A lot of people  -  I don’t want this to sound trivial -  but a lot of people are switching to these really long putters, very unattractive. It’s weird. You see these great players with these really long putters, because they can’t sink three-footers anymore. And, I hate it. I am a traditionalist. I have so many fabulous friends who happen to use four-character extensions, but I am a traditionalist.

**Comment by ssaavedra** [comment]
I think the canonical way would be all-caps surname-only. `.TRUMP`, like constants.

Small caps may not carry enough power.

A more archaic mode could probably be activated with a `.Drumph` extension (see https://youtu.be/DnpO_RTSNmQ).

**Comment by CryoBrown** [comment]
The extension doesn't matter,  nothing checks it

**Comment by eamanu** [comment]
.trump, like it

**Comment by samshadwell** [comment]
See a76f078
