### ISSUE TITLE
Should have a modulo operator, what keyword should it be?

### ISSUE THREAD

**Issue by numinit** [samshadwell/TrumpScript#24]
What if `percent` was used as a modulo operator? It doesn't make much sense, though... what other words could we use?

```ts
make great 1000010
make world 1000000

i want to make america great percent world;
say america
America is great.
```

**Comment by CryoBrown** [comment]
n mod a = n - (floor(a/n) * n)

so really, we need to get a good way to round down (or up, then we can subtract one)
and then we support the ability to perform modulo arithmetic. The problem is that division at the moment isn't rounding either way, and this "feature" actually allows people to construct floats from integer literals, following the rules of integer only but preserving the ability to create floats

**Comment by CryoBrown** [comment]
"But that sounds so complicated and hard!"

Yeah. I firmly oppose a modulo operator on those grounds alone.

**Comment by numinit** [comment]
:+1:
