### ISSUE TITLE
Failed to consume

### ISSUE THREAD

**Issue by Jonathan50** [samshadwell/TrumpScript#87]
I am trying to run this program:
```trump
Make Donald 200000000
As long as Donald is very much greater than 10000000; do this:
Donald is Donald minus 1000000 but
say Donald is very nice
Amazing!
America is great.
```
but get this error:
```
failed to consume 10, got 40instead.
is_error
passed in parenthetical with more than one expression
failed to consume 11, got 5instead.
is_error
Compiled, starting execution
-------------------

Traceback (most recent call last):
  File "src/trumpscript/main.py", line 32, in <module>
    main()
  File "src/trumpscript/main.py", line 29, in main
    Compiler().compile(sys.argv[1])
  File "src/trumpscript/compiler.py", line 20, in compile
    exec(compile(modu, filename="<ast>", mode="exec"))
TypeError: expected some sort of expr, but got <_ast.Assign object at 0x7fb6bae52550>
```

**Comment by CryoBrown** [comment]
failed to get a LParen token, got a Word instead. This is because you don't have a comma after as long as. Also this program won't work until I find the time to actually put less than and greater than comparisons into the parser.

Also it's improperly written on other fronts as well. As we don't have the greater than or less than features built, the syntax for them isn't quite nailed down, but the code you wrote is trying to assign > 1000000 to Donald.

**Comment by CryoBrown** [comment]
Failed to consume 11 got 5 is when you encounter greater than rather than the expected semicolon

**Comment by rdoyle1** [comment]
I know that this is a few months late, but I believe this bug was fixed when greater than and less than were added in on Jan. 27th. The same example as above, with correct syntax, would be

```
Make Donald 200000000
As long as, Donald "is" very much greater than 10000000; do this:
Donald is, Donald minus 1000000; but
say Donald "is" very nice
Amazing!
America is great.
```

**Comment by Jonathan50** [comment]
Thanks! Should I close this?

**Comment by samshadwell** [comment]
Yup, looks like this works now!
